### ISSUE TITLE
TypeError: PokemonGOAPI.POGOProtos.Inventory.Item.InventoryItem is not a constructor

### ISSUE THREAD

**Issue by UAVova** [stoffern/pokemongo-api#102]
```
D:\Downloads\pokemongo-api-master\pokemongo-api-master>npm run example

> pokemongo-api@0.0.0-semantically-released example D:\Downloads\pokemongo-api-master\pokemongo-api-master
> babel-node example/example.js

[i] Logging with user: email@gmail.com
[i] Received Google access token!
[!] Endpoint set: https://pgorelease.nianticlabs.com/plfe/1/rpc
[i] Received OK: GetPlayerResponse
[i] Received OK: GetInventoryResponse
TypeError: PokemonGOAPI.POGOProtos.Inventory.Item.InventoryItem is not a constructor
    at index.js:105:45
    at Array.reduce (native)
    at PokemonGOAPI._callee2$ (index.js:102:38)
    at tryCatch (D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\regenerator-runtime\runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\regenerator-runtime\runtime.js:95:21)
    at step (index.js:11:1)
    at index.js:11:1
    at run (D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\core-js\modules\es6.promise.js:87:22)
    at D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\core-js\modules\es6.promise.js:100:28
```

**index.js**:105
`inventory.items[obj[itemData[key]]] = new PokemonGOAPI.POGOProtos.Inventory.Item.InventoryItem`

**Comment by stoffern** [comment]
Update to latest version
