### ISSUE TITLE
TypeError: Illegal buffer

### ISSUE THREAD

**Issue by UAVova** [stoffern/pokemongo-api#104]
Revision: 78f0557e7b1605fbe14bb7d210165b056518a6c2

\> **npm run example**

```
> pokemongo-api@0.0.0-semantically-released example D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master
> babel-node example/example.js

[i] Logging with user: email@gmail.com
[i] Received Google access token!
[!] Endpoint set: https://pgorelease.nianticlabs.com/plfe/516/rpc
[i] Received OK: GetPlayerResponse
[!] Response error!
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\bytebuffer\dist\bytebuffer-node.js:346:19)
    at Function.Message.decode (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\protobufjs\dist\protobuf.js:2930:84)
    at API.js:35:55
    at Array.map (native)
    at Connection._callee$ (API.js:29:14)
    at tryCatch (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\regenerator-runtime\runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\regenerator-runtime\runtime.js:95:21)
    at step (API.js:9:1)
```

**Comment by UAVova** [comment]
Adding
`await new Promise(resolve => setTimeout(resolve, 3000))`
before each api call in **example.js** helps.

**Comment by stoffern** [comment]
Duplicate issue: https://github.com/stoffern/pokemongo-api/issues/84
@UAVova always check the issues list before creating new issues.
