### ISSUE TITLE
Error: Illegal wire type

### ISSUE THREAD

**Issue by UAVova** [stoffern/pokemongo-api#106]
```
[!] Response error!
Error: Illegal wire type for field Message.Field .POGOProtos.Data.Capture.CaptureAward.activity_type: 2 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\protobufjs\dist\protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\protobufjs\dist\protobuf.js:3233:48)
    at ProtoBuf.Reflect.ElementPrototype.decode (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\protobufjs\dist\protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\protobufjs\dist\protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\protobufjs\dist\protobuf.js:3238:45)
    at Function.Message.decode (D:\Downloads\pokemongo-api-master (1)\pokemongo-api-master\node_modules\protobufjs\dist\protobuf.js:2933:37)
    at API.js:35:55
    at Array.map (native)
    at Connection._callee$ (API.js:29:14)
```

Console DIR:
```
{ CatchPokemonResponse:
   { status: 1,
     miss_percent: 0.5797366499900818,
     captured_pokemon_id: Long { low: 0, high: 0, unsigned: true },
     capture_award: null } }
```

It happens with **example.js** on this line:
`await pokemon.catch(ball.item_id).catch(console.log)`

However, pokemon catched successfully. I have no idea why it is outputting an error.. Any ideas?

**Comment by KyleRoss** [comment]
As mentioned here: https://github.com/stoffern/pokemongo-api/blob/master/src/Pokemon.js#L86

The first time calling `.catch()` ends with an error, but the second call to `.catch()` will be successful.

**Comment by stoffern** [comment]
Duplicate issue.
Follow this issue here https://github.com/stoffern/pokemongo-api/issues/84
