### ISSUE TITLE
[Bug] Can't use the library without regeneratorRuntime in my own project

### ISSUE THREAD

**Issue by jgoux** [stoffern/pokemongo-api#150]
Hello,

By just importing the library, I have this error : 
```
  ReferenceError: regeneratorRuntime is not defined
  at /home/jgx/Projects/jgoux/push-and-go/server/node_modules/pokemongo-api/dist/Auth.js:45:36
  at /home/jgx/Projects/jgoux/push-and-go/server/node_modules/pokemongo-api/dist/Auth.js:96:6
  at Object.<anonymous> (/home/jgx/Projects/jgoux/push-and-go/server/node_modules/pokemongo-api/dist/Auth.js:184:2)
  at Module._compile (module.js:541:32)
  at Module._extensions..js (module.js:550:10)
  at Object.require.extensions.(anonymous function) [as .js] (/home/jgx/Projects/jgoux/push-and-go/server/node_modules/babel-register/lib/node.js:156:7)
  at Module.load (module.js:456:32)
  at tryModuleLoad (module.js:415:12)
  at Function.Module._load (module.js:407:3)
  at Module.require (module.js:466:17)
```

It seems that we have to use the regenerator runtime in our own project to be able to use your library.

I'm on node v6 and I'd prefer not to use it as v6 supports generators. :smile 

I use babel only to fill the gap with the few ES6 missing features : 
```json
{
  "presets": ["es2015-node6"],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
```

**Comment by gallexme** [comment]
try putting 
require("babel-core/register");
require("babel-polyfill");
ontop of everything inside your "main.js" of your project
this worked for me

also you probably need this in your .babelrc presets
"es2015",
 "stage-0"

**Comment by stoffern** [comment]
```
npm i -D babel-preset-es2015
npm i -D babel-preset-stage-0
```

in .babelrc
```
{
  "presets": [ "es2015", "stage-0" ]
}
```

**Comment by jgoux** [comment]
As I said, I'd prefer to use nodejs v6 native implementation instead of transpiling here.

IMHO a library should be ready to be consumed without changing the build step of the consumer (or no build step at all, ES5 ready).

Ideally I'd just have to do `var PokeAPI = require('pokemongo-api')` and be ready to go.

Is there a way that you include regenerator in the build ? Or maybe modify the presets to turn the async functions into standard Promise ?

**Comment by stoffern** [comment]
@jgoux ah sorry my bad.
When we publish to NPM all the ES6 code is transpiled into ES5.
you can see it in your `node_modules\pokemongo-api\dist`

If you want to use ES5 do as @gallexme said:
```
npm i -D babel-core
npm i -D babel-polyfill
```
Create index.js and add on top of the index file:
```
require("babel-core/register");
require("babel-polyfill");
var PokeAPI = require('pokemongo-api')
```

**Comment by jgoux** [comment]
@stoffern I'm really sorry, I think I'm not clear at all. xD

My main issue with this solution is that it will turn my whole codebase into ES5, only because I want to use your library.

If we could find a way to turn your library ES6 -> ES5 without needing regenerator, I could consume it without including "babel-polyfill", and keep my codebase with all the native implementation ([node v6 supports 95% of ES6 specs](http://node.green)).

**Comment by stoffern** [comment]
transform-runtime over polyfill? thats new to me.. i should read about it i guess 
good it worked out for you :wink:

**Comment by jgoux** [comment]
I think this plugin has to be used by you, the library author. ^^
So the babel-runtime doesn't leak into userland, and we can require the library without doing anything else. :+1:

**Comment by stoffern** [comment]
ah, let me look at it tomorrow

**Comment by jackypan1989** [comment]
hope it would help @jgoux

**Comment by stoffern** [comment]
@jgoux PR merged, can you try it out now? :wink:
