### ISSUE TITLE
Illegal wire type for field Message.Field .POGOProtos.Data.PokemonData.additional_cp_multiplier: 5 (0 expected)

### ISSUE THREAD

**Issue by maxnowack** [stoffern/pokemongo-api#54]
Today I'm getting a new Proto-Error:
````
Error: Illegal wire type for field Message.Field .POGOProtos.Data.PokemonData.additional_cp_multiplier: 5 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at /Users/maxnowack/Code/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:78:29
    at Array.map (native)
    at Connection._callee$ (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:68:26)
    at tryCatch (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:29:191)
    at /Users/maxnowack/Code/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:29:368
    at run (/Users/maxnowack/Code/pokemongo-api-example-project/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/maxnowack/Code/pokemongo-api-example-project/node_modules/core-js/modules/es6.promise.js:100:28
````

Since it is a parsing error in PokemonData, it occurs everytime I get the inventory.
Any ideas?

**Comment by stoffern** [comment]
@maxnowack what function are you calling?
i think it has something to do with this commit https://github.com/stoffern/pokemongo-api/commit/d802bf55a0cf70285d80fffc37f764d2a218648d

**Comment by maxnowack** [comment]
I'm using the `GetInventory` method. I'm on the latest version on npm. It seems that the commit you mentioned wasn't published to npm yet

**Comment by maxnowack** [comment]
Oh, it's published. Please let me check if it's working

**Comment by stoffern** [comment]
I am trying to get onto automatic npm publishing, but for now the .git is more up to date.. :)

**Comment by maxnowack** [comment]
No, it's not. Even if I change it back to `int32`

**Comment by stoffern** [comment]
it is working like a charm here:
```
[i] Received OK: GetPlayerResponse
[i] Received OK: GetInventoryResponse
```
are you banned?

**Comment by maxnowack** [comment]
Hmm strange ...
No I'm not banned and everything else is working fine

**Comment by stoffern** [comment]
try deleting the line `additional_cp_multiplier`
in `POGOProtos.Data.PokemonData`

**Comment by maxnowack** [comment]
Yeah, that works :) Maybe it should be marked as `optional`

**Comment by stoffern** [comment]
yeah, we should probably do that.
can you try to set it to:
`optional float additional_cp_multiplier = 28;`
and see if that works?

**Comment by maxnowack** [comment]
Yes, this works
