### ISSUE TITLE
Response error when trying to catch pokemon 

### ISSUE THREAD

**Issue by RafalWilinski** [stoffern/pokemongo-api#77]
I'm using standard example provided with this repository.

This is what happens when I'm trying to catch one of `catchable_pokemons`.
```
for (let pokemon of cell.catchable_pokemons) {
        console.log(pokemon);
        await pokemon.encounterAndCatch().catch(err => console.log(err))
}
```
Output:
```
Pokemon {
  spawn_point_id: '47045b37f01',
  encounter_id: Long { low: -839243475, high: 950341743, unsigned: true },
  pokemon_id: 21,
  expiration_timestamp_ms: Long { low: -1, high: -1, unsigned: false },
  latitude: 52.408770537209655,
  longitude: 16.92496333519808,
  num: '021',
  name: 'Spearow',
  img: 'http://www.serebii.net/pokemongo/pokemon/021.png',
  type: 'Normal / Flying',
  height: '0.30 m',
  weight: '2.0 kg',
  candy: '50 Spearow Candy',
  egg: '2 km',
  multipliers: [ 2.66, 2.68 ],
  weaknesses: [ 'Electric', 'Rock' ],
  next_evolution: [ { num: '022', name: 'Fearow' } ],
  catchable: true,
  parent:
   PokemonGOAPI {
     player:
      Player {
        parent: [Circular],
        playerInfo: [Object],
        Auth: [Object],
        surroundings: [Object] },
     api:
      Connection {
        parent: [Circular],
        endPoint: 'https://pgorelease.nianticlabs.com/plfe/23/rpc',
        auth_ticket: [Object] },
     map: PlayerMap {},
     logged: false,
     debug: true,
     useHeartBeat: false } }
[i] Received OK: EncounterResponse
[!] Response error!
```

Message is not so descriptive so I digged down to `error` object inside `API.js` file.
This is how it looks like:
```
Error: Illegal wire type for field Message.Field .POGOProtos.Data.Capture.CaptureAward.activity_type: 2 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/Rafal/Node/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/Rafal/Node/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3233:48)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/Rafal/Node/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/Rafal/Node/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/Rafal/Node/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at Function.Message.decode (/Users/Rafal/Node/pokemongo-api-example-project/node_modules/protobufjs/dist/protobuf.js:2933:37)
    at /Users/Rafal/Node/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:74:67
    at Array.map (native)
    at Connection._callee$ (/Users/Rafal/Node/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:68:26)
```

**Comment by stoffern** [comment]
Seems to be a bug.. Try setting optional repeated... Here: https://github.com/stoffern/pokemongo-api/blob/master/POGOProtos/Data/Capture/CaptureAward.proto#L7

**Comment by InsOpDe** [comment]
did not work for me

**Comment by maxnowack** [comment]
It seems that `repeated` is implicitly `optional`
http://stackoverflow.com/a/25637833/1624176

**Comment by stoffern** [comment]
Then it is the type maybe?

**Comment by maxnowack** [comment]
the type of `activity_type` is `.POGOProtos.Enums.ActivityType`.
maybe a missing value in the enum? do you have an idea how we can test that?

**Comment by stoffern** [comment]
It is here: https://github.com/stoffern/pokemongo-api/blob/master/POGOProtos/Enums/ActivityType.proto

**Comment by stoffern** [comment]
This issue is related to #23
Please follow the issue there
