### ISSUE TITLE
Babel Polyfill throws error.

### ISSUE THREAD

**Issue by DaVarga** [stoffern/pokemongo-api#94]
Since commit 264135f i got following error:

```
$ babel-node src/main.js 
.../node_modules/babel-polyfill/lib/index.js:12
  throw new Error("only one instance of babel-polyfill is allowed");
  ^

Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (.../node_modules/babel-polyfill/lib/index.js:12:9)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:159:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (src/main.js:1:1)

```

**Comment by stoffern** [comment]
New commit to fix the issue: b2113e6b5dcba2b6f5f729070e3a8e890bd6e1da

**Comment by DaVarga** [comment]
Still fails with the same error.

**Comment by stoffern** [comment]
@DaVarga trying again, does it work now

**Comment by DaVarga** [comment]
it does, thanks.
