### ISSUE TITLE
CatchPokemonMessage#spawn_point_guid is not a field: undefined

### ISSUE THREAD

**Issue by delmotte** [stoffern/pokemongo-api#97]
I got a problem when trying to catch a pokemon, with both 'catch' and 'encounterAndCatch' method

here is the error : 

```
Error: .POGOProtos.Networking.Requests.Messages.CatchPokemonMessage#spawn_point_guid is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/Users/delmotte/Project/PokemonGO/bot-test/node_modules/protobufjs/dist/protobuf.js:2472:35)
    at MessagePrototype.set (/Users/delmotte/Project/PokemonGO/bot-test/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/Users/delmotte/Project/PokemonGO/bot-test/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at /Users/delmotte/Project/PokemonGO/bot-test/node_modules/pokemongo-api/dist/API.js:286:37
    at Array.map (native)
    at Connection._serializeRequest (/Users/delmotte/Project/PokemonGO/bot-test/node_modules/pokemongo-api/dist/API.js:276:19)
    at Connection._callee2$ (/Users/delmotte/Project/PokemonGO/bot-test/node_modules/pokemongo-api/dist/API.js:125:28)
    at tryCatch (/Users/delmotte/Project/PokemonGO/bot-test/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/delmotte/Project/PokemonGO/bot-test/node_modules/regenerator-runtime/runtime.js:336:22)
```

I found the solution in 'catch' method, change field 'spawn_point_guid' by 'spawn_point_id' :
```
return this.parent.Call([{
                  request: 'CATCH_POKEMON',
                  message: {
                    encounter_id: this.encounter_id,
                    pokeball: pokeball || 1, // 2 for grate ball
                    normalized_reticle_size: Math.min(1.95, _randgen2.default.rnorm(1.9, 0.05)),
                    spawn_point_guid: this.spawn_point_id, // ----------- THIS LINE ---------
                    hit_pokemon: true,
                    spin_modifier: Math.min(0.95, _randgen2.default.rnorm(0.85, 0.1)),
                    normalized_hit_position: 1.0
                  }
                }]);
```

**Comment by mash1t** [comment]
There still is an other error occuring after applying the fix you mentioned:

[i] >>>>>>>>>>>>>>> Catching pokemon  Magikarp
[i] Received OK: EncounterResponse
[!] Response error!
Error: Illegal wire type for field Message.Field .POGOProtos.Data.Capture.CaptureAward.activity_type: 2 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/protobufjs/dist/protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/protobufjs/dist/protobuf.js:3233:48)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at Function.Message.decode (/Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/protobufjs/dist/protobuf.js:2933:37)
    at /Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/pokemongo-api/dist/API.js:76:67
    at Array.map (native)
    at Connection._callee$ (/Volumes/Data/Entwicklung/Projects/privat/pokemon-farm/node_modules/pokemongo-api/dist/API.js:70:26)

**Comment by stoffern** [comment]
@delmotte Added fix here: 5947bdaa5b51eeb8ce381e71c50644c81f77f734

**Comment by delmotte** [comment]
@mash1t Yes but if you look at your pokemon number, it has been catched ;)

**Comment by stoffern** [comment]
@mash1t we know of this error. The pokemon it catched but by a wierd reason we cant decode the response in 50% of the time it fails. Follow the issue here: https://github.com/stoffern/pokemongo-api/issues/77
Closing this issue as it is fixed.
